### ISSUE TITLE
IndexOutOfRangeException

### ISSUE THREAD

**Issue by Midnoclose** [tc-mods/BaboonAPI#5]
I have a specific track that is unable to be clicked in the track select menu. When I click it, it goes to an adjacent song instead.

```
[Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
LevelSelectController.populateSongNames (System.Boolean do_full_anim) (at <9cbe48c3a3ab459fa119b1e8fc760d5e>:0)
LevelSelectController.advanceSongs (System.Int32 dir, System.Boolean do_full_anim) (at <9cbe48c3a3ab459fa119b1e8fc760d5e>:0)
LevelSelectController.clickNext () (at <9cbe48c3a3ab459fa119b1e8fc760d5e>:0)
LevelSelectController.Update () (at <9cbe48c3a3ab459fa119b1e8fc760d5e>:0)
```

This error shows up in the log every time i try to click the track.

**Comment by hedgehog1029** [comment]
that's a bit of a funny base game issue it looks like, base game blindly indexes an array with the difficulty value. I may look into sanitizing that in future
